#!/bin/bash
set -e

# Declare requirements
function requires() {
    if ! command -v $1 &>/dev/null; then
        echo "Requires $1"
        exit 1
    fi
}

requires mill
requires riscv32-unknown-elf-objdump

# Check if at least one test name is provided
if [ "$#" -eq 0 ]; then
    echo "Error: No test name provided."
    echo "Usage: simulate <test-name>"
    exit 1
fi

# Run the given tests
mkdir -p test_run_dir
for test in "$@"; do
    echo "Running test: $test"
    if [ ! -f "test/e2e-tests/resources/c/$test.c" ]; then
        echo "- Error: Test file test/e2e-tests/resources/c/$test.c does not exist."
        continue
    fi

    # Build and run tests
    mill --color false --disable-ticker test.runMain e2e.RunCFile test/e2e-tests/resources/c/$test.c --verbose 2>&1 | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g' > test_run_dir/$test.log
    riscv32-unknown-elf-objdump -d test/e2e-tests/generated/$test.elf > test_run_dir/$test.dump

    # Output the file path
    echo "- Log file available at: test_run_dir/$test.log"
    echo "- Dump file available at: test_run_dir/$test.dump"
done